title: CalculatedRi.sk
url: "https://calculatedri.sk"
baseurl: ""
author: ""
theme: minima
header_pages:
  - about.md
  - cases.md
  - docs.md
  - calculator.md
collections:
 cases:
   output: true
   permalink: /:collection/:name
   order:
    - tutorial.md
excerpt_separator: <!--more-->