name: GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: sudo npm run build-calculator
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./blog
          destination: ./blog/_site
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "blog/_site"
      - uses: actions/deploy-pages@v2
